/*
 * Copyright 2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.aot.generate;

/**
 * Enumeration that represents the artifact types generated by the Spring AOT engine.
 *
 * @author Sebastien Deleuze
 */
public enum GeneratedArtifact {

	/**
	 * Source code (and related class files) for bean registration generated based on
	 * an AOT computation of the application context where configuration classes conditions
	 * are computed at build-time.
	 */
	BEAN_REGISTRATION,

	/**
	 * Classpath indexes like the {@code META-INF/spring.components} file generated by
	 * the Spring AOT engine useful from skipping classpath or JPA entity runtime scanning.
	 */
	CLASSPATH_INDEXES,

	/**
	 * Predefined classes such as CGLIB classes generated by the Spring AOT engine.
	 */
	PREDEFINED_CLASSES,

	/**
	 * Reachability metadata generated by the Spring AOT engine based on the runtime hints,
	 * required for GraalVM native image support.
	 */
	REACHABILITY_METADATA
}
